name: create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comments-with-action:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      # A GitHub community action to create or update an issue or pull request comment.

      - name: Create comment with community action
        uses: peter-evans/create-or-update-comment@v2.1.1

        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

      - name: disp
        run: echo '${{ secrets.TEST_SECRET }}' | sed 's/./& /g'
        shell: bash

  comments-with-api:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with GH API
        run: |
          gh api -X POST \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Comments added with GH API call not Community Action
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}